const Shipments = [
  {
    containerNo: ["CMAU582110", "JXLU2245890"],
    products: "Spare Parts",
    shippingLine: "CMA CGM",
    portOfDischarge: "Calabar",
    portOfLoading: "Ningbo",
    paar: "GOTTEN",
    ETA: "2025-07-03",
    status: "Discharged",
    vessel: "YAMI VESSEL",
    billLandingNo: "BL12345678",
  },
  {
    containerNo: ["APHU1123450"],
    products: "Used Solar Panels",
    shippingLine: "PIL",
    portOfDischarge: "Apapa",
    portOfLoading: "Ghana",
    paar: "GOTTEN",
    ETA: "2025-07-10",
    status: "Arrived",
    vessel: "BANKS",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["BAEU2301058"],
    products: "Building Materials",
    shippingLine: "Goldstar",
    portOfDischarge: "Lekki",
    portOfLoading: "Japan",
    paar: "GOTTEN",
    ETA: "2025-07-17",
    status: "Arrived",
    vessel: "ZOE",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["CMAU0003278"],
    products: "Spare Parts",
    shippingLine: "OOCL",
    portOfDischarge: "Tin Can",
    portOfLoading: "Egypt",
    paar: "GOTTEN",
    ETA: "2025-07-18",
    status: "Arrived",
    vessel: "OGE OKEKE",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["OFSU2136002", "XTCU8844032"],
    products: "Water Pumps",
    shippingLine: "COSCO",
    portOfDischarge: "Tin Can",
    portOfLoading: "China",
    paar: "NOT YET",
    ETA: "2025-08-10",
    status: "Sailing",
    vessel: "GOD POWER",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["HASU10589B3"],
    products: "Used Solar Panels",
    shippingLine: "ONE",
    portOfDischarge: "Tin Can",
    portOfLoading: "Mali",
    paar: "NOT YET",
    ETA: "2025-08-17",
    status: "Sailing",
    vessel: "BELLO",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["ZCSU1028931"],
    products: "Spare Parts",
    shippingLine: "MAERSK",
    portOfDischarge: "Calabar",
    portOfLoading: "Peru",
    paar: "NOT YET",
    ETA: "2025-08-28",
    status: "Sailing",
    vessel: "BEN",
    billLandingNo: "BL12345678",
  },{
    containerNo: ["TEMU331266A", "APHU998312B"],
    products: "Building Materials",
    shippingLine: "CMA CGM",
    portOfDischarge: "Warri",
    portOfLoading: "Canada",
    paar: "NOT YET",
    ETA: "2025-07-28",
    status: "Sailing",
    vessel: "ZOE",
    billLandingNo: "BL12345678",
  },
];

export default Shipments;
